object Versions {
    internal const val kotlinVersion = ""
    internal const val gradleVersion = "7.0.4"
    internal const val kotlinGradlePlugin = "1.5.20"
    internal const val coreVersion = "1.8.0"
    internal const val coreRole = "1.0.0"
    internal const val coreAnimation = "1.0.0-beta01"
    internal const val splashScreen = "1.0.0-rc01"
    internal const val animationTesting = "1.0.0-beta01"
    internal const val dataStore = "1.0.0"
    internal const val lifecycle_version = "2.5.0-rc01"
    internal const val arch_version = "2.1.0"
    internal const val appCompat = "1.4.2"
    internal const val material = "1.6.1"
    internal const val constraintLayout = "2.1.4"
    internal const val roomVersion = "2.4.2"
    internal const val fragment = "1.4.1"
    internal const val hilt = "2.38.1"
    internal const val metrics = "1.0.0-alpha01"
    internal const val navigation = "2.4.2"
    internal const val paging = "3.1.1"
    internal const val pagingCompose = "1.0.0-alpha15"
    internal const val recyclerview = "1.2.1"
    internal const val recyclerviewSelection = "1.1.0"
    internal const val securityCrypto = "1.0.0"
    internal const val identityCredentials = "1.0.0-alpha03"
    internal const val appAuthenticator = "1.0.0-alpha02"
    internal const val swipeRefresh = "1.1.0"
    internal const val coroutines = "1.3.9"
    internal const val coilImageLoader = "2.1.0"
    internal const val retrofit = "2.9.0"
    internal const val okLogging = "4.9.0"
    internal const val timber = "5.0.1"
    internal const val firebase = "18.2.11"

    internal const val firebaseCore = "17.2.0"
    internal const val firebaseAnalytics = "17.2.0"
    internal const val crashAnalytics = "2.10.1"

    internal const val jUnit = "4.13.2"
    internal const val jUnitTestExt = "1.1.3"
    internal const val espressoCore = "3.4.0"
    internal const val jUnitExtension = "1.1.1"
    internal const val uiautomator = "2.2.0"
    internal const val espresso = "3.2.0"
    internal const val mockito = "2.22.0"
    internal const val mockitoAll = "1.10.19"
    internal const val hamcrest = "1.3"
    internal const val atslRunner = "1.1.0-alpha1"
    internal const val atslRules = "1.1.0-alpha1"
    internal const val mockWebserver = "3.8.1"
    internal const val robolectric = "4.8.1"

}