object Versions {
    internal const val kotlinVersion = ""
    internal const val gradleVersion = "7.0.4"
    internal const val kotlinGradlePlugin = "1.5.20"
    internal const val coreVersion = "1.8.0"
    internal const val coreRole = "1.0.0"
    internal const val coreAnimation = "1.0.0-beta01"
    internal const val splashScreen = "1.0.0-rc01"
    internal const val animationTesting = "1.0.0-beta01"
    internal const val dataStore = "1.0.0"
    internal const val lifecycle_version = "2.5.0-rc01"
    internal const val arch_version = "2.1.0"
    internal const val appCompat = "1.4.2"
    internal const val material = "1.6.1"
    internal const val constraintLayout = "2.1.4"
    internal const val roomVersion = "2.4.2"
    internal const val paging = "2.5.0-alpha02"
    internal const val fragment = "1.4.1"
    internal const val hilt = "2.38.1"

    internal const val jUnit = "4.13.2"
    internal const val jUnitTestExt = "1.1.3"
    internal const val espressoCore = "3.4.0"

}